version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_PORT=3000
    command: [nginx-debug, '-g', 'daemon off;']

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: coldcold
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    
volumes:
  mongo-db: